function phi = PHI(dx,dy,mu,alpha,in5)
%PHI
%    PHI = PHI(DX,DY,MU,ALPHA,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-May-2022 16:50:38

%Version: 0.9
u1 = in5(1,:);
u2 = in5(2,:);
u3 = in5(3,:);
u4 = in5(4,:);
u5 = in5(5,:);
u6 = in5(6,:);
u7 = in5(7,:);
u8 = in5(8,:);
t2 = dx.^2;
t3 = u1.^2;
t4 = u2.^2;
t5 = u3.^2;
t6 = u4.^2;
t7 = u5.^2;
t8 = u6.^2;
t9 = u7.^2;
t10 = u8.^2;
et1 = mu.*t3.*1.2e+1+mu.*t4.*6.0+mu.*t5.*1.2e+1+mu.*t6.*6.0+mu.*t7.*1.2e+1+mu.*t8.*6.0+mu.*t9.*1.2e+1+mu.*t10.*6.0+alpha.*t2.*t3.*2.0+alpha.*t2.*t4.*2.0+alpha.*t2.*t5.*2.0+alpha.*t2.*t6.*2.0+alpha.*t2.*t7.*2.0+alpha.*t2.*t8.*2.0+alpha.*t2.*t9.*2.0+alpha.*t2.*t10.*2.0-mu.*u1.*u3.*2.4e+1-mu.*u1.*u5.*1.2e+1-mu.*u2.*u4.*1.2e+1+mu.*u1.*u7.*1.2e+1-mu.*u2.*u6.*6.0+mu.*u3.*u5.*1.2e+1+mu.*u2.*u8.*6.0-mu.*u3.*u7.*1.2e+1+mu.*u4.*u6.*6.0-mu.*u4.*u8.*6.0-mu.*u5.*u7.*2.4e+1-mu.*u6.*u8.*1.2e+1+alpha.*t2.*u1.*u3.*2.0+alpha.*t2.*u1.*u5+alpha.*t2.*u2.*u4.*2.0+alpha.*t2.*u1.*u7.*2.0+alpha.*t2.*u2.*u6+alpha.*t2.*u3.*u5.*2.0+alpha.*t2.*u2.*u8.*2.0+alpha.*t2.*u3.*u7;
et2 = alpha.*t2.*u4.*u6.*2.0+alpha.*t2.*u4.*u8+alpha.*t2.*u5.*u7.*2.0+alpha.*t2.*u6.*u8.*2.0;
phi = (mu.*(u1+u3-u5-u7).*(u2-u4-u6+u8))./4.0+(dy.*(et1+et2))./(dx.*3.6e+1)+(dx.*mu.*(t3+t4.*2.0+t5+t6.*2.0+t7+t8.*2.0+t9+t10.*2.0+u1.*u3-u1.*u5+u2.*u4.*2.0-u1.*u7.*2.0-u2.*u6.*2.0-u3.*u5.*2.0-u2.*u8.*4.0-u3.*u7-u4.*u6.*4.0-u4.*u8.*2.0+u5.*u7+u6.*u8.*2.0))./(dy.*6.0);
